name: aiops-q4

channels:
  - conda-forge

dependencies:
  - python=3.13
  - pip=25.*
  - numpy=2.5.1
  - scipy=1.18.0
  - pandas=2.3.3
  - scikit-learn=1.9.0
  - joblib=1.5.3
  - matplotlib=3.11.0
  - ipykernel=7.3.0
  - jupyterlab=4.6.3
  - pip:
      - mlflow==3.15.1
      - cloudpickle==3.1.2
      - dvc==3.67.1
      - dvc-ssh==4.3.0   # SSH remote
      - dvc-s3==3.3.0    # S3 remote
